version: '3'
services:
  app:
    container_name: mini-wallet
    build: .
    ports:
      - 9000:9000
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - db
    networks:
      - fullstack


  db:
      image: mysql
      restart: on-failure
      container_name: wallet_sql
      ports:
        - 3306:3306
        - 33060:33060
      environment:
        - MYSQL_DATABASE=wallet_db
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - database_mysql:/var/lib/mysql
      networks:
        - fullstack

volumes:
    api:
    database_mysql:

networks:
  fullstack:
    driver: bridge