CREATE TABLE wallets (
  `id` CHAR(36) NOT NULL,
  `owned_by` CHAR(36) NOT NULL,
  `token` CHAR(36) NOT NULL UNIQUE,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `balance` DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
  `enabled_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` CHAR(36) NOT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` CHAR(36) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
