CREATE TABLE `customers` (
    `customer_id` bigint unsigned NOT NULL AUTO_INCREMENT,
    `company_name` varchar(50) NOT NULL,
    `first_name` varchar(30) NOT NULL,
    `last_name` varchar(50) NOT NULL,
    `billing_address` varchar(255) NOT NULL,
    `province` varchar(20) NOT NULL,
    `zip_code` varchar(20) NOT NULL,
    `email` varchar(75) NOT NULL,
    `company_website` varchar(200) NOT NULL,
    `phone_number` varchar(30) NOT NULL,
    `fax_number` varchar(30),
    `ship_address` varchar(255) NOT NULL,
    `ship_city` varchar(50) NOT NULL,
    `ship_province` varchar(50) NOT NULL,
    `ship_zip_code` varchar(20) NOT NULL,
    `ship_phone_number` varchar(30) NOT NULL,
    `is_deleted` tinyint(1) DEFAULT 0,
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_by` bigint NOT NULL DEFAULT 0,
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_by` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;